# Setup
title:               planetspaceball
tagline:             'here'
description:         ''
url:                 http://planetspaceball.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              psb
  url:               https://planetspaceball.github.io
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #
