# Setup
title:               planetspaceball
tagline:             ''
description:         ''
url:                 https://planetspaceball.github.io
baseurl:             'https://planetspaceball.github.io'
paginate:            5
permalink:           pretty
pages_list:       
  About: '/about'
  Archive: '/archive'
  Wiki: '/wiki'
  Feed: '/atom.xml'
  

# About/contact
author:
  name:              psb
  url:               https://planetspaceball.github.io
  email: 

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #
